# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Potluck',
        ),
    ]
