# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='cardnumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='checkedOutTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shareShack.Borrower'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dueBack',
            field=models.DateField(blank=True, null=True),
        ),
    ]
