# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0002_auto_20180401_0301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkOuts',
            new_name='CheckOut',
        ),
        migrations.RenameModel(
            old_name='returns',
            new_name='Return',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='checkedOutTo',
            new_name='checked_Out_To',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dateAdded',
            new_name='date_Added',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dueBack',
            new_name='due_Back',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='inStock',
            new_name='in_Stock',
        ),
        migrations.AlterField(
            model_name='item',
            name='writtenId',
            field=models.CharField(max_length=30, unique=True, verbose_name='Written ID'),
        ),
    ]
