# Generated by Django 2.0 on 2018-04-30 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0003_auto_20180401_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareShack.Borrower'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_Out_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareShack.Borrower'),
        ),
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(choices=[('CA', 'Catering'), ('LA', 'Landscaping'), ('RE', 'Recreation'), ('MA', 'Maintenance'), ('FU', 'Furniture')], default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contactPerson',
            field=models.TextField(blank=True, help_text='names,emails,phone,preference, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareShack.Borrower'),
        ),
        migrations.AlterField(
            model_name='return',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
