# Generated by Django 2.0 on 2018-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0005_auto_20180520_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='dateJoined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='dateIssued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_Added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='dateReturned',
            field=models.DateField(auto_now_add=True),
        ),
    ]
