# Generated by Django 2.0 on 2018-05-30 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0006_auto_20180529_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='items',
        ),
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(default='empty default', on_delete=django.db.models.deletion.PROTECT, to='shareShack.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='staff',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
