# Generated by Django 2.0 on 2018-05-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0007_auto_20180529_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shareShack.Item'),
        ),
    ]
