# Generated by Django 2.0 on 2018-05-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareShack', '0008_auto_20180529_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='return',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='return',
            name='items',
        ),
        migrations.RemoveField(
            model_name='return',
            name='staff',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
