# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodCosts', '0003_auto_20180709_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_unit',
            field=models.CharField(default='bun', max_length=200),
            preserve_default=False,
        ),
    ]
